account/urls.py
from django.urls import path
from .import views

app_name = 'account'

urlpatterns = [
    path("login/", views.login_View , name='login'),
    path("signup/", views.signup_view , name='signup'),
    path("logout/", views.logout_view , name='logout')
]

blog/urls.py
from django.urls import path
from .import views

app_name = "blog"

urlpatterns = [
    path("",views.blog_list,name="blog_list"),
    path("<int:id>",views.blog_detail,name="blog_detail"),
]

bodyland/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path , include
from django.shortcuts import redirect
from django.views.generic import TemplateView


urlpatterns = [
    path('', lambda request: redirect('/home/')),
    path('admin/', admin.site.urls),
    path('home/', include('blog.urls')),
    path('music/', include('music.urls')),
    path('workout/', include('workout.urls')),
    path('account/', include('account.urls')),
    path('product/', include('product.urls')),
    path('course/', include('course.urls')),
    path('rules/', TemplateView.as_view(template_name="rules.html"), name="rules"),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/_footer.html
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" />

  <style>
    .contact-us .section {
      font-size: 100px;
      color: #28a745;
    }
    .social-links {
      margin-top: 40px;
      direction: rtl;
      text-align: right;
    }
    
    .social-link {
      display: inline-block;
      margin-left: 16px;
      font-size: 28px;
      color: #6a6a6a;
      position: relative;
      transition: color 0.3s ease;
    }
    
    .social-link::after {
      content: '';
      display: block;
      width: 0%;
      height: 2px;
      background-color: currentColor;
      transition: width 0.3s ease;
      margin-top: 4px;
    }
    
    .social-link:hover {
      color: #6c63ff;
    }
    
    .social-link:hover::after {
      width: 100%;
    }
    
    .social-link.instagram:hover {
      color: #e1306c;
    }
    
    .social-link.github:hover {
      color: #333;
    }
    
    .social-link.telegram:hover {
      color: #0088cc;
    }
    
    .social-link.phone:hover {
      color: #28a745;
    }
  </style>
</head>

<body>
  <div class="contact-us section" id="contact" style="direction: rtl; padding-right: 150px;">
    <div class="container" style="direction: rtl;">
      <div class="row" style="direction: rtl;">
        <div class="col-lg-7 align-self-center" style="direction: rtl; " >
          <div class="section-heading" style="text-align: right; direction: rtl;  ">
            <h6 style="font-size: 45px;">ارتباط با ما</h6>
            <h2 style="font-size: 25px; color: black !important; font-weight: 300;">در صورت وجود هرگونه سوال یا نیاز به راهنمایی، با ما در تماس باشید.</h2>

            <div class="social-links">
              <a href="https://www.instagram.com/soheil_t_kd?igsh=MTFtZHcwMDk4Y2Nidw==" target="_blank" class="social-link instagram"><i class="fab fa-instagram"></i></a>
              <a href="https://github.com/SoheilTK99" target="_blank" class="social-link github"><i class="fab fa-github"></i></a>
              <a href="https://t.me/Soheil_Talebee" target="_blank" class="social-link telegram"><i class="fab fa-telegram"></i></a>
              <a href="tel:09100385781" class="social-link phone"><i class="fas fa-phone"></i></a>
            </div>
          </div>
        </div>
        <div class="col-lg-5">
          <div class="contact-us-content" style="text-align: right; direction: rtl; height: 300px;">
            <form id="contact-form" action="" method="post">
              <div class="row">
                <div class="col-lg-12">
                  <fieldset>
                    <input type="name" name="name" id="name" placeholder="نام شما" autocomplete="on" required />
                  </fieldset>
                </div>
                <div class="col-lg-12">
                  <fieldset>
                    <input type="text" name="email" id="email" pattern="[^ @]*@[^ @]*" placeholder="پست الکترونیک" required="" />
                  </fieldset>
                </div>
                <div class="col-lg-12">
                  <fieldset>
                    <textarea name="message" id="message" placeholder="پیام شما"></textarea>
                  </fieldset>
                </div>
                <div class="col-lg-12">
                  <fieldset>
                    <button type="submit" id="form-submit" class="orange-button">ارسال پیام</button>
                  </fieldset>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

<footer>
  <div class="container">
    <div class="col-lg-12">
      <div class="copyright">
        <p>
          کليه حقوق اين سایت متعلق به بادی لند میباشد ©<br />
          طراحی توسط: <a href="https://github.com/SoheilTK99" target="_blank">سهیل طالبی</a>
        </p>
      </div>
    </div>
  </div>
</footer>

templates/partials/_header.html
{% load static %}
<header class="header-area header-sticky background-header">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <nav class="main-nav">
          <div class="nav-right">
            <a href="/home/#top" class="logo"><img src="/static/assets/images/logo.png" alt="Logo" style="width:200px;" /></a>
          </div>

          <div class="nav-center">
            <ul class="nav">
              <!-- START: New Wrapper Div -->
              <div class="main-menu-items">
                <li>
                  <a href="/rules/" class="smart-scroll" data-target="rule">قوانین و مقررات</a>
                </li>
                <li>
                  <a href="/home/#blogs" class="smart-scroll" data-target="blogs">مجله</a>
                </li>
                <li>
                  <a href="/home/#events" class="smart-scroll" data-target="events">دوره ها</a>
                </li>
                <li>
                  <a href="/product/#step4" class="smart-scroll" data-target="#step4">فروشگاه</a>
                </li>
                <li>
                  <a href="/workout/" class="smart-scroll" data-target="top">برنامه تمرینی</a>
                </li>
              </div>
              <!-- END: New Wrapper Div -->

              <li class="mobile-only-icon theme-toggle-mobile">
                <a href="javascript:void(0);" id="themeToggleMobile">
                  <img id="moonIconMobile" src="/static/assets/images/dark-mode.png" alt="Dark Mode" style="width: 24px; vertical-align: middle; margin-left: 8px;" />
                  <img id="sunIconMobile" src="/static/assets/images/sun.png" alt="Light Mode" style="width: 24px; vertical-align: middle; margin-left: 8px; display: none;" />
                  تغییر حالت تم
                </a>
              </li>

              <li class="mobile-only-icon user-menu-mobile">
                {% if is_logged_in %}
                  <a href="{% url 'account:logout' %}">
                    <img src="/static/assets/images/logged-in2.png" alt="User" style="width: 24px; vertical-align: middle; margin-left: 8px;" />
                    خروج از حساب
                  </a>
                {% else %}
                  <a href="{% url 'account:login' %}?next={{ request.path }}">
                    <img src="/static/assets/images/user.png" alt="User-logo" style="width: 24px; vertical-align: middle; margin-left: 8px;" />
                    ورود / ثبت‌نام
                  </a>
                {% endif %}
              </li>
            </ul>
          </div>

          <div class="nav-left">
            <div class="search-input">
              <form class="search-input-form" action="#">
                <input type="text" placeholder="جستجو کنید" name="searchKeyword" style="text-align: right;" />
                <i class="fa fa-search"></i>
              </form>
            </div>

            <ul class="user-menu">
              {% if is_logged_in %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown"><img src="/static/assets/images/logged-in2.png" alt="User" style="width: 36px;" /></a>
                  <div class="dropdown-menu text-right" style="direction: rtl;">
                    <a class="dropdown-item" href="{% url 'account:logout' %}">خروج</a>
                  </div>
                </li>
              {% else %}
                <li class="nav-item">
                  <a href="{% url 'account:login' %}?next={{ request.path }}"><img src="/static/assets/images/user.png" alt="User-logo" style="width: 38px;" /></a>
                </li>
              {% endif %}
            </ul>

            <img src="/static/assets/images/line.png" alt="line" style="width: 36px;" />

            <button id="themeToggle" style="background: none; border: none; cursor: pointer;">
              <img id="moonIcon" src="/static/assets/images/dark-mode.png" alt="Dark Mode" style="width: 32px; display: inline;" />
              <img id="sunIcon" src="/static/assets/images/sun.png" alt="Light Mode" style="width: 32px; display: none;" />
            </button>
          </div>

          <a class="menu-trigger">
            <img id="hamburger-img" src="{% static 'assets/images/hamburger-icon.png' %}" alt="Open Menu" />
            <img id="close-img" src="{% static 'assets/images/close-icon.png' %}" alt="Close Menu" style="display: none;" />
          </a>
        </nav>
      </div>
    </div>
  </div>
</header>

<style>
  .main-nav {
    display: flex;
    justify-content: space-between;
    align-items: center;
    height: 100px;
  }
  
  .nav-left {
    display: flex;
    justify-content: flex-start;
    align-items: center;
    gap: 0px;
    margin-bottom: 20px;
  }
  
  /* منو دقیقا وسط */
  .nav-center {
    padding-top: 0px;
    padding-bottom: 35px;
    padding-left: 150px;
  }
  
  .nav-center .nav {
    display: flex;
    gap: 0px;
    list-style: none;
    padding: 0;
    margin: 0;
  }
  
  /* آیتم‌های منو */
  .nav li {
    display: flex;
    align-items: center;
  }
  
  .nav-right {
    display: flex;
    justify-content: flex-end;
    align-items: center; /* آیتم‌ها رو در راستای عمودی وسط قرار می‌ده */
    gap: 20px; /* فاصله بین آیتم‌ها رو تنظیم می‌کنه */
  }
  
  .nav-right .nav {
    display: flex;
    gap: 20px;
    list-style: none;
    padding: 0;
    margin: 0;
  }
  
  .logo img {
    height: 80px;
    object-fit: contain;
    margin-left: 0px;
    margin-bottom: 50px;
  }
  
  .search-input {
    position: relative;
    width: 220px;
    padding-left: 10px;
  }
  
  .search-input input {
    width: 100%;
    padding: 10px 35px 10px 12px;
    border-radius: 25px;
    border: none;
    outline: none;
    background: rgba(255, 255, 255, 0.1);
    color: white;
    font-size: 14px;
  }
  
  .search-input input::placeholder {
    color: rgba(255, 255, 255, 0.62);
    opacity: 1;
  }
  
  .search-input i.fa-search {
    position: absolute;
    right: 12px;
    top: 50%;
    transform: translateY(-50%);
    color: white;
    pointer-events: none;
    font-size: 16px;
  }
  
  /* Dropdown */
  .nav-item.dropdown {
    position: relative;
  }
  
  .dropdown-item:hover {
    background-color: #ffffff !important;
    color: #000000 !important;
    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.15);
    transition: all 0.2s ease-in-out;
  }
  
  .nav-item.dropdown .dropdown-menu {
    display: none;
    position: absolute;
    top: 120%;
    left: 50%;
    transform: translateX(-50%);
    background: transparent;
    padding: 0;
    border: none;
    box-shadow: none;
  }
  
  .nav-item.dropdown.show .dropdown-menu {
    display: block;
  }
  
  .dropdown-item {
    background-color: white !important;
    color: black !important;
    border-radius: 25px;
    text-align: center;
    padding: 3px 20px 10px 20px !important;
    margin: 0 auto;
    width: fit-content;
  }
  
  .nav-item.dropdown {
    display: flex;
    align-items: center;
    height: 100%;
  }
  
  .nav-item.dropdown .nav-link {
    display: flex;
    align-items: center;
    padding: 0 4px 0 12px;
    height: 100%;
    color: white;
    font-size: 14px;
    line-height: 1;
    text-decoration: none;
    background: transparent;
    border: none;
  }
  
  .nav li {
    display: flex;
    align-items: center;
    height: 100%;
  }
  
  .header-area .main-nav .nav-left {
    order: 1;
  }
  .header-area .main-nav .nav-center {
    order: 2;
  }
  .header-area .main-nav .nav-right {
    order: 3;
  }
  
  .header-area .main-nav .nav-left {
    display: flex;
    align-items: center;
  }
  .header-area .main-nav .nav-left .search-input {
    order: 2;
  }
  .header-area .main-nav .nav-left > *:not(.search-input) {
    order: 1;
  }
  .menu-trigger {
    display: none !important;
  } 
  
  .main-menu-items {
      display: flex;
  }


  .menu-trigger,
  .mobile-only-icon {
      display: none !important;
  }
  
  /* ===================================
         Mobile Style
         =================================== */
  @media (max-width: 992px) {
    /* قفل کردن اسکرول صفحه اصلی وقتی منو باز است */
    body.menu-is-open {
      overflow: hidden;
    }
  
    /* ۱. مخفی کردن آیتم‌های دسکتاپ */
    .header-area .main-nav .nav,
    .header-area .main-nav .nav-left,
    .header-area .main-nav .nav-center {
      display: none !important;
    }
  
    /* ۲. چیدمان اصلی هدر */
    .header-area .main-nav {
      display: flex;
      justify-content: space-between;
      align-items: center;
      width: 100%;
      height: 80px;
      padding: 0 15px;
      box-sizing: border-box;
    }
  
    /* ۳. استایل دکمه همبرگری */
    .header-area .main-nav .menu-trigger {
      display: flex !important;
      align-items: center;
      justify-content: center;
      cursor: pointer;
      z-index: 1001;
      width: 40px;
      height: 40px;
    }
    .header-area .main-nav .menu-trigger img {
      width: 25px;
      height: 25px;
    }
  
    /* ۴. تنظیم اندازه لوگو */
    .header-area .main-nav .logo img {
      width: 150px !important;
      margin: 0 !important;
      padding-bottom: 25px;
    }
  
    /* ۵. استایل منوی بازشونده (تمام صفحه و وسط‌چین) */
    .header-area.menu-open .nav-center {
      display: flex !important;
      justify-content: center;
      align-items: flex-start; /* <<<< آیتم‌ها را به بالای منو می‌چسباند */
      position: fixed;
      top: 80px;
      left: 0;
      width: 100%;
      height: calc(100vh - 80px);
      background-color: #cfcfcfff;
      z-index: 1000;
      overflow-y: auto;
      border-radius: 20px;
      padding-right: 20px !important;
      padding-left: 20px;
    }
    .header-area.menu-open .nav {
      display: flex !important;
      flex-direction: column !important;
      direction: rtl !important; /* <<<< اصلاحیه کلیدی اینجاست */
      width: 85%;
      max-width: 320px;
    }
    .header-area.menu-open .main-menu-items {
      display: flex;
      flex-direction: column-reverse; /* فقط آیتم‌های اصلی را برعکس می‌کند */
    }
  
    .header-area.menu-open .nav li {
      text-align: center;
      width: 100%;
      padding: 0; /* <<<< پدینگ از آیتم لیست حذف می‌شود */
      border-bottom: 1px solid rgba(183, 183, 183, 1);
    }
    .header-area.menu-open .nav li a {
      padding: 18px 10px; /* <<<< پدینگ به لینک اضافه می‌شود */
      display: block; /* <<<< برای اینکه کل سطح قابل کلیک باشد */
      width: 100%;
      font-size: 16px; /* فونت بزرگتر برای خوانایی بهتر */
      color: #000000ff;
    }
  
    .header-area.menu-open .nav li.user-menu-mobile {
      background-color: transparent;
      border: 2px solid #ff9900ff;
      border-radius: 60px;
      margin: 20px auto 0 auto;
      width: 80%;
  
      box-sizing: border-box;
      height: 50px;
    }
  
    .header-area.menu-open .nav li.user-menu-mobile a {
      color: #000000ff;
      font-weight: bold;
      justify-content: center;
      margin-bottom: 40px;
    }
  
    /* حذف افکت هاور */
    .header-area.menu-open .nav li.user-menu-mobile a:hover {
      color: #ffffff;
    }
  
    .header-area.menu-open .nav .mobile-only-icon {
      display: flex !important;
      justify-content: center;
      align-items: center;
    }
  }
</style>